from .group import Group
from .user_admin import Administrator
from .user_teacher import Teacher
from .user_student import Student
from .module import Module
from .seance import Seance
from .absence import Absence
from .justification import Justification
from .alert import Alert
